if (!window.QUESTIONS_MODULES) window.QUESTIONS_MODULES = {};

window.QUESTIONS_MODULES["Opérateur de Machines"] = [
    { q: "Quel est le risque principal lors de l'utilisation d'une machine avec des pièces en rotation ?", o: ["A) Le risque de poussière", "B) Le risque d'entraînement, de happement ou de sectionnement des membres", "C) La surchauffe des néons"], r: "B" },
    { q: "Peut-on retirer un carter de protection pour travailler plus vite sur une machine ?", o: ["A) Oui, si on fait attention", "B) Non, il est strictement interdit de neutraliser ou retirer un dispositif de sécurité", "C) Uniquement si le chef donne son accord"], r: "B" },
    { q: "À quoi sert le bouton d'arrêt d'urgence de type 'coup de poing' ?", o: ["A) À allumer la machine le matin", "B) À couper immédiatement l'alimentation électrique de la machine en cas de danger imminent", "C) À appeler les secours"], r: "B" },
    { q: "Pourquoi est-il interdit de porter des vêtements amples ou des bijoux près d'une machine ?", o: ["A) Parce qu'ils peuvent se salir", "B) Parce qu'ils augmentent considérablement le risque de happement par les pièces en mouvement", "C) Pour des raisons d'esthétique"], r: "B" },
    { q: "Quelle précaution obligatoire doivent prendre les opérateurs ayant des cheveux longs ?", o: ["A) Les teindre en une couleur visible", "B) Les attacher ou les coiffer sous une casquette ou un filet pour éviter l'entraînement", "C) Ne pas travailler"], r: "B" },
    { q: "Que devez-vous faire avant d'effectuer le nettoyage ou le débourrage d'une machine ?", o: ["A) Ralentir la vitesse de la machine", "B) Arrêter complètement la machine et s'assurer de sa consignation électrique/mécanique", "C) Mettre des gants plus épais"], r: "B" },
    { q: "Que signifie la 'mise en conformité' d'une machine de travail ?", o: ["A) Changer sa couleur", "B) Veiller à ce qu'elle réponde aux normes de sécurité techniques et juridiques en vigueur", "C) Augmenter sa vitesse"], r: "B" },
    { q: "Qu'est-ce qu'une commande 'bimanuelle' sur une machine ?", o: ["A) Une commande qui s'active avec un pied", "B) Un système obligeant l'opérateur à utiliser ses deux mains pour protéger ses doigts", "C) Une télécommande sans fil"], r: "B" },
    { q: "Si une machine émet un bruit anormal ou des vibrations suspectes, quelle est la bonne réaction ?", o: ["A) Continuer le travail", "B) Arrêter la machine, baliser le poste et signaler immédiatement l'anomalie", "C) Mettre un casque"], r: "B" },
    { q: "Pour enlever des copeaux métalliques ou des débris sur une table de machine, on utilise :", o: ["A) Ses mains nues", "B) Un outil adapté (brosse, pince, balayette) machine à l'arrêt", "C) Une soufflette d'air comprimé"], r: "B" },
    { q: "Quelle est l'utilité d'un dispositif de protection 'interverrouillé' sur une porte de machine ?", o: ["A) Bloquer la porte pour empêcher le vol", "B) Empêcher le démarrage tant que la porte est ouverte, ou arrêter la machine si on l'ouvre", "C) Éclairer l'intérieur"], r: "B" },
    { q: "Qui est autorisé à utiliser une machine industrielle complexe ou dangereuse ?", o: ["A) N'importe quel employé de passage", "B) Uniquement le personnel formé, qualifié et désigné par l'employeur", "C) Le personnel d'entretien"], r: "B" },
    { q: "Qu'indique un voyant lumineux ROUGE fixe sur le panneau de contrôle d'une machine ?", o: ["A) Que la machine fonctionne parfaitement", "B) Un défaut, une alarme ou un état de danger nécessitant une attention immédiate", "C) Que la machine est en veille"], r: "B" },
    { q: "Quel EPI est requis pour protéger le visage des projections de morceaux de matière ?", o: ["A) Un simple masque anti-poussière", "B) Des lunettes de protection à écrans latéraux ou un écran facial (visière)", "C) Des bouchons d'oreilles"], r: "B" },
    { q: "La notice d'instructions d'une machine (manuel utilisateur) doit être :", o: ["A) Rangée dans le bureau du directeur", "B) Accessible aux opérateurs et aux équipes de maintenance à proximité de la machine", "C) Jetée après l'installation"], r: "B" },
    { q: "Que devez-vous vérifier sur le bouton d'arrêt d'urgence avant de démarrer une machine ?", o: ["A) S'il est bien propre", "B) Qu'il est déverrouillé et pleinement fonctionnel", "C) Sa date de fabrication"], r: "B" },
    { q: "Qu'est-ce qu'une zone dangereuse sur une machine ?", o: ["A) La zone où l'on stocke les produits", "B) Tout espace à l'intérieur ou autour de la machine où une personne est exposée à un risque", "C) Le sol autour de la machine"], r: "B" },
    { q: "Que doit faire un opérateur s'il constate qu'une grille de protection s'est desserrée ?", o: ["A) Mettre du scotch", "B) Stopper le travail, resserrer la grille si autorisé ou alerter la maintenance", "C) Attendre l'accident"], r: "B" },
    { q: "Le port de gants de protection est-il recommandé pour travailler sur un tour en rotation ?", o: ["A) Oui, pour ne pas se salir", "B) Non, il est interdit car les mailles peuvent s'accrocher et entraîner la main", "C) Uniquement les gants en laine"], r: "B" },
    { q: "À quelle fréquence l'opérateur doit-il nettoyer son poste de travail et sa machine ?", o: ["A) Une fois par an", "B) Régulièrement, au minimum à la fin de chaque poste", "C) Uniquement quand la machine tombe en panne"], r: "B" }
];
