if (!window.QUESTIONS_MODULES) window.QUESTIONS_MODULES = {};

window.QUESTIONS_MODULES["Assemblage au Mât"] = [
    { q: "Quel est le risque majeur spécifique lors du montage d'un mât en sections ?", o: ["A) Le bruit du vent", "B) L'effondrement de la structure ou la chute d'éléments lourds", "C) La surchauffe des outils"], r: "B" },
    { q: "Quelle mesure de sécurité est obligatoire au sol au droit d'un mât en cours de montage ?", o: ["A) Installer une bâche anti-poussière", "B) Mettre en place une zone d'exclusion balisée pour interdire l'accès sous les charges", "C) Garer les véhicules"], r: "B" },
    { q: "Comment sécuriser une clé à choc ou un outil à main utilisé en haut du mât ?", o: ["A) En le tenant très fort avec les deux mains", "B) En l'attachant à une dragonne ou une lanière reliée au harnais ou à la structure", "C) En le mettant dans sa poche ouverte"], r: "B" },
    { q: "Lors de l'ascension d'un mât sur une échelle fixe sans crinoline, quel système utilise-t-on ?", o: ["A) Une simple corde de maçon", "B) Un antichute guidé sur rail ou câble rigide (ligne de vie verticale)", "C) Aucun système"], r: "B" },
    { q: "Quelle est la règle d'or lors du déplacement sur la structure du mât avec une double longe ?", o: ["A) Déconnecter les deux connecteurs pour aller plus vite", "B) Toujours garder au moins un des deux mousquetons ancré à la structure", "C) Attacher les deux mousquetons sur son propre harnais"], r: "B" },
    { q: "Quelle est l'utilité d'un couple de serrage précis (clé dynamométrique) lors de l'assemblage d'un mât ?", o: ["A) Faire gagner du temps", "B) Garantir la solidité mécanique de la structure face aux vibrations et au vent", "C) Rendre les boulons plus jolis"], r: "B" },
    { q: "En cas de détection d'une fissure sur une bride d'assemblage d'un mât, que faut-il faire ?", o: ["A) Continuer le montage et mettre de la peinture", "B) Stopper immédiatement l'assemblage et remplacer la pièce défectueuse", "C) Serrer le boulon plus fort"], r: "B" },
    { q: "Quel équipement permet de lever les sections du mât depuis le sol de manière contrôlée ?", o: ["A) Une cordelette simple tirée à la main", "B) Un treuil de levage ou une grue avec des élingues certifiées", "C) Une échelle"], r: "B" },
    { q: "Quel type de casque est recommandé pour les opérateurs travaillant sur un mât ?", o: ["A) Un casque de chantier classique sans jugulaire", "B) Un casque type alpiniste avec jugulaire résistante pour ne pas le perdre la tête en arrière", "C) Une casquette renforcée"], r: "B" },
    { q: "Quelle condition météorologique impose l'arrêt immédiat des travaux sur un mât ?", o: ["A) Un grand soleil", "B) Des vents violents ou un risque d'orage/foudre", "C) Une température de 20°C"], r: "B" },
    { q: "Que signifie l'expression 'travailler en tension' pour une structure haubanée ?", o: ["A) Travailler sous l'effet du stress", "B) Régler la tension correcte des câbles de maintien (haubans) pour stabiliser le mât", "C) Utiliser des outils électriques"], r: "B" },
    { q: "Pourquoi le port de chaussures de sécurité avec un profil de semelle antidérapant est-il vital sur un mât ?", o: ["A) Pour ne pas salir la structure", "B) Pour éviter les glissades sur les barreaux ou les surfaces métalliques humides", "C) Pour marcher plus vite au sol"], r: "B" },
    { q: "Lors du levage d'une section de mât, qui dirige la manœuvre ?", o: ["A) Tout le monde en même temps en criant", "B) Un chef de manœuvre unique (chef d'équipe) par signaux ou radio", "C) Le conducteur de la grue"], r: "B" },
    { q: "À quoi sert une 'broche de centrage' lors de l'alignement de deux sections de mât ?", o: ["A) À visser les écrous", "B) À aligner les trous des boulons en sécurité avant de mettre les fixations définitives", "C) À mâturer la hauteur"], r: "B" },
    { q: "Peut-on stocker des boulons en vrac sur une plateforme non sécurisée en haut du mât ?", o: ["A) Oui, si on fait attention", "B) Non, ils doivent être placés dans des sacs à outils ou sacoches fermées et attachées", "C) Uniquement les petits boulons"], r: "B" },
    { q: "Qu'est-ce qu'un hauban sur un mât ?", o: ["A) Un outil de serrage", "B) Un câble d'ancrage en acier destiné à stabiliser la structure verticale face au vent", "C) Une échelle de secours"], r: "B" },
    { q: "Quelle vérification doit être faite sur les boulons d'ancrage de la base du mât (fondation) ?", o: ["A) Vérifier s'ils sont bien peints", "B) S'assurer de leur serrage au couple et de l'absence de corrosion ou de jeu", "C) Les recouvrir de terre"], r: "B" },
    { q: "Lors d'un travail sur un mât de télécommunication, quel risque invisible s'ajoute à la chute ?", o: ["A) Le risque d'exposition aux rayonnements électromagnétiques (ondes des antennes)", "B) Le risque d'asphyxie", "C) Le risque d'inondation"], r: "A" },
    { q: "Quelle est la règle concernant le port du harnais lors de l'utilisation d'une nacelle élévatrice pour monter sur un mât ?", o: ["A) Le harnais est inutile car la nacelle a des garde-corps", "B) Le harnais est obligatoire et doit être attaché au point d'ancrage prévu dans la nacelle", "C) On peut l'attacher directement sur le mât"], r: "B" },
    { q: "Qui doit vérifier la conformité du matériel de levage utilisé pour l'assemblage du mât ?", o: ["A) Le client à la fin des travaux", "B) Une personne compétente ou un organisme agréé (vérification périodique à jour)", "C) Le fabricant uniquement à la vente"], r: "B" }
];
